### ISSUE TITLE
Handling float32 wav files

### ISSUE THREAD

**Issue by f0k** [gudgud96/frechet-audio-distance#11]
Floating-point PCM WAV files are currently not handled correctly. Such files are not very common, but are created when passing float32 numpy arrays to `scipy.io.wav.write()` or `torchaudio.save()`.

What currently happens [on loading](https://github.com/gudgud96/frechet-audio-distance/blob/eba2d8e/frechet_audio_distance/fad.py#L24) is this:

1. ```python
   wav_data, sr = sf.read(fname, dtype='int16')
   ```
   This reads the floating point samples and then rounds them to the nearest integer (so `wav_data` will usually only contain -1, 0, and +1 samples), in line with the [documentation of `soundfile.read()`](https://python-soundfile.readthedocs.io/en/0.11.0/#soundfile.read).
2. ```python
   assert wav_data.dtype == np.int16, 'Bad sample type: %r' % wav_data.dtype
   ```
   As far as I can tell, this can never happen, because the dtype is enforced in the previous line.
3. ```python
   wav_data = wav_data / 32768.0  # Convert to [-1.0, +1.0]
   ```
   This converts the samples to -1/32768, 0 and +1/32768.

One solution would be to not pass a `dtype` argument to `soundfile.read()` and then convert whatever comes back, something like:
```python
wav_data, sr = sf.read(fname)
if np.issubdtype(data.dtype, np.floating):
    wav_data = np.asarray(wav_data, dtype=np.float32)
else:
    wav_data = np.divide(wav_data, np.iinfo(wav_data.dtype).max, dtype=np.float32)
```

Another solution would be to pass `dtype=np.float32` to `soundfile.read()`. Was there a specific reason against this route? With an example OGG file, I've seen that `dtype=np.float32` produced values between -1.2 and +1.4, while `dtype=np.int16` scaled it by 32767 and clipped too high and too low values. Not sure if the latter is preferable in any case.

**Comment by gudgud96** [comment]
@f0k Thanks for the catch!

I personally think loading with `dtype=np.float32` should suffice. But to be more cautious, I would need to double check the effect of this precision issue on the output embeddings. The original FAD repo assumes a signed 16-bit PCM too when [generating test files](https://github.com/google-research/google-research/blob/master/frechet_audio_distance/gen_test_files.py#L72). Will need to check on this and get back to you!

**Comment by f0k** [comment]
For 16-bit PCM WAV, changing to `dtype=np.float32` and removing your scaling should have no effect:
```
import numpy as np
import scipy.io.wavefile as wav
import soundfile as sf
x = np.sin(10*np.pi*np.linspace(0, 1, 100))
x = (x * np.iinfo(np.int16).max).astype(np.int16)
wav.write('/dev/shm/foo.wav', 16000, x)
a = sf.read('/dev/shm/foo.wav', dtype=np.int16)
b = sf.read('/dev/shm/foo.wav', dtype=np.float32)
print(np.allclose(a / 32768, b)  # True
print(np.allclose(a / 32767, b))  # False
```
So it uses the same scaling factor that you use, i.e., the resulting samples will be the same (and so should the output embeddings).

For file formats other than 16-bit PCM WAV, it may make a difference (e.g., for OGG Vorbis, the scaling factor seems to be 32767, and `dtype=np.int16` results in clipping while `dtype=np.float32` does not).

**Comment by gudgud96** [comment]
I checked the embeddings of a 16-bit PCM WAV and a 32-bit floating point WAV of a sample, and the difference is non-trivial.

```python
x = np.sin(10 * np.pi * np.linspace(0, 1, 16000))
x_16bit_pcm = (x * np.iinfo(np.int16).max).astype(np.int16)
write('x_16bit_pcm.wav', 16000, x_16bit_pcm)
write('x.wav', 16000, x)

# read as 16-bit PCM
wav_data, sr = sf.read('x_16bit_pcm.wav', dtype=np.int16)
wav_data = wav_data / 32768.0  # Convert to [-1.0, +1.0]

# read as 32-bit float
wav_data2, sr = sf.read('x.wav', dtype=np.float32)

frechet = FrechetAudioDistance(
    model_name="vggish",
    use_pca=False, 
    use_activation=False,
    verbose=False
)
embd_16_pcm = frechet.model.forward(wav_data, 16000).cpu().detach().numpy().squeeze()
embd_32_fp = frechet.model.forward(wav_data2, 16000).cpu().detach().numpy().squeeze()
print(embd_16_pcm[:64])
print(embd_32_fp[:64])
```

Results as below:
```
// 16-bit PCM embedding
[-0.29444298  0.31406254  0.02483752 -0.090868    0.06529082 -0.28654444
 -0.33299792  0.39594865 -0.07714616 -0.19858798 -0.5212506  -0.40436786
 -0.0874465  -0.23646921 -0.02078038 -0.247128    0.1537666   0.08483589
  0.02312446 -0.06836903  0.06259377 -0.40276277  0.06264522 -0.22392777
  0.09245223  0.6951835  -0.29809463 -0.1102495   0.02722163 -0.27168906
 -0.24573931  0.5747994   0.2957354   0.49476987  0.2060358  -0.05682266
 -0.20026815 -0.07456811 -0.18887843 -0.1261819  -0.08551532 -0.02244058
 -0.01141691 -0.22868317 -0.04672366 -0.08877963  0.5527732   0.530049
 -0.19277602  0.32908213 -0.11641581 -0.3583722  -0.13155212 -0.00204306
  0.17920929 -0.3431649   0.27042657  0.1163296   0.6207167   0.01475862
  0.09565882 -0.31576133 -0.22859657 -0.33793807]

// 32-bit floating point embedding
[-0.31887862  0.34905574  0.01981959 -0.10582782  0.07321109 -0.31688538
 -0.33307537  0.358396   -0.07114525 -0.20952123 -0.53261256 -0.4194343
 -0.09213831 -0.22993445 -0.02598457 -0.24774633  0.15535757  0.06992441
  0.01378287 -0.04282311  0.09152284 -0.39358455  0.05524025 -0.21363363
  0.09429073  0.70238686 -0.3031646  -0.10573053  0.03345974 -0.2664482
 -0.24774227  0.5403322   0.30338302  0.48034593  0.2284123  -0.05141349
 -0.22474813 -0.06161593 -0.16687305 -0.11633921 -0.10495272 -0.01417476
 -0.00127251 -0.21953088 -0.03740227 -0.08737643  0.53624547  0.5223452
 -0.18035531  0.33213484 -0.124896   -0.35727316 -0.1677065  -0.00930559
  0.15758955 -0.33775073  0.2817479   0.13047487  0.6306114   0.03382191
  0.07356875 -0.31775308 -0.25386396 -0.33566797]
```

For this issue, I can move towards loading with `dtype=np.float32`. This can then handle floating point PCM WAVs correctly. A PR will be raised soon.

However, do note that in any case I can't guarantee the correctness / reproducibility of the model embedding if a non-16-bit-PCM WAV is used as input. Users would be using the embedding at their own risk.

**Comment by gudgud96** [comment]
Fixed as per https://github.com/gudgud96/frechet-audio-distance/pull/12, close for now.

**Comment by f0k** [comment]
> I checked the embeddings of a 16-bit PCM WAV and a 32-bit floating point WAV of a sample, and the difference is non-trivial.

Interesting! There were some possibly unwanted differences in your code (starting from `x`, `wav_data` was multiplied by 32767, then quantized, then divided by 32768), but actually the quantization seems to be the culprit:
```
from frechet_audio_distance import FrechetAudioDistance

x = np.sin(10 * np.pi * np.linspace(0, 1, 16000))
x16 = ((x * 32767).astype(np.int16) / 32767)

frechet = FrechetAudioDistance(
    model_name="vggish",
    use_pca=False,
    use_activation=False,
    verbose=False
)
embd32 = frechet.model.forward(x.astype(np.float32), 16000).cpu().detach().numpy().squeeze()
embd16 = frechet.model.forward(x16.astype(np.float32), 16000).cpu().detach().numpy().squeeze()
print(embd16[:64])
print(embd32[:64])
```
Correcting the scaling only slightly changes the 16-bit embeddings compared to yours (e.g., the first number is `-0.29443464`). So the only modification left is the 16-bit quantization.

> However, do note that in any case I can't guarantee the correctness / reproducibility of the model embedding if a non-16-bit-PCM WAV is used as input.

One learning is that it is important to have the two sets of audio files in the same format: If the set of reference recordings was 16-bit quantized, then the evaluation recordings must also be 16-bit quantized, because VGGish is sensitive to that.
