### ISSUE TITLE
Does the requirement for transformers<=4.30 necessary?

### ISSUE THREAD

**Issue by y10ab1** [gudgud96/frechet-audio-distance#26]
Thanks for the great work!

I'm just wondering if the transformers version <=4.30 should be necessary or not. 
This is because there are newer audio models (e.g. generative model or other models like Encodec in transformers) that are only available in newer versions of transformers.

Is there potential for conflict between the newer version of transformers and your implementation?

**Comment by gudgud96** [comment]
@y10ab1 I did a further check, and I find that the fixated `transformers` version originates from `laion_clap`: https://github.com/LAION-AI/CLAP/blob/main/requirements.txt#L16. Unfortunately it needs to be relaxed on the CLAP side.

I believe Encodec should not have restriction on the `transformers` version. So overall, our library should be able to run fine. Do you have a specific case where there is a conflict?

**Comment by y10ab1** [comment]
Just the error message from the dependency check occurs when I install a newer version of `transformers` (Encodec needs`transformers` >=4.31 )
I believe the package can still function properly though.

<img width="1135" alt="截圖 2024-02-08 晚上7 43 06" src="https://github.com/gudgud96/frechet-audio-distance/assets/94939112/a1fee278-4283-40b9-a876-351b5a160bec">

**Comment by gudgud96** [comment]
I see, you mean the `transformers` version of Encodec. 
Unfortunately there's not much I can do on this side, but feel free to raise an issue on `laion_clap`'s repo regarding the fixated version.

**Comment by y10ab1** [comment]
Got it, thanks!
