### ISSUE TITLE
Loosen Numpy Dependency Requirement

### ISSUE THREAD

**Issue by OoiHS** [gudgud96/frechet-audio-distance#32]
**The Issue**
As of release version 0.3.1, the numpy requirement was
`numpy==1.23.4`
This requirement is too strict, and creates numpy dependency conflicts with other libraries.

**Suggested Solution**
Loosen the numpy requirement to
`numpy>=1.23.4`

The same suggestion also apply for the scipy requirement, currently it is
`scipy==1.10.1`

Thank you.

**Comment by gudgud96** [comment]
Thanks for raising this. Makes sense, the versions should have been outdated, happy to take a PR if you are willing to contribute. Or else, I can have a look some time later this week.

**Comment by OoiHS** [comment]
Added PR https://github.com/gudgud96/frechet-audio-distance/pull/33

**Comment by OoiHS** [comment]
merged
